<?php

namespace Oro\Bundle\CustomerBundle\Service;

use Symfony\Bridge\Twig\Attribute\Template;

class CustomerService
{
    #[Template]
    public function processAction(): array
    {
        return [];
    }
}

-----
<?php

namespace Oro\Bundle\CustomerBundle\Service;

use Symfony\Bridge\Twig\Attribute\Template;

class CustomerService
{
    #[Template]
    public function processAction(): array
    {
        return [];
    }
}
